// This file is auto-generated by @hey-api/openapi-ts

export type AuthEmailLoginDto = {
  email: string;
  password: string;
};

export type AuthRegisterLoginDto = {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
};

export type AuthUpdateDto = {
  photo?: FileDto;
  firstName?: string;
  lastName?: string;
  email?: string;
  password?: string;
  oldPassword?: string;
};

export type CreateCustomerDto = {
  note?: string;
  address: string;
  email?: string;
  phone: string;
  name: string;
};

export type CreateOrderDto = {
  customer: CustomerDto;
  item: Array<OrderItem>;
  totalAmount: number;
  deliveryAddress: string;
};

export type CreateOrderHistoryDto = {
  changeByUser: UserDto;
  order: OrderDto;
  /**
   * Trạng thái đơn hàng trong lịch sử thay đổi
   */
  status: OrderStatusEnum;
};

export type CreateUserDto = {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  photo?: FileDto;
  role?: RoleDto;
  status?: StatusDto;
};

export type Customer = {
  note: string | null;
  address: string;
  email: string | null;
  phone: string;
  name: string;
  id: string;
  createdAt: string;
  updatedAt: string;
};

export type CustomerDto = {
  id: string;
};

export type EnumerateCountOrderDto = {
  enumerateBy?: string;
  startDate: string;
  endDate: string;
  status?: string;
};

export type FileDto = {
  id: string;
};

export type FileResponseDto = {
  file: FileType;
};

export type FileType = {
  id: string;
  path: string;
};

export type InfinityPaginationCustomerResponseDto = {
  data: Array<Customer>;
  hasNextPage: boolean;
};

export type InfinityPaginationOrderHistoryResponseDto = {
  data: Array<OrderHistory>;
  hasNextPage: boolean;
};

export type InfinityPaginationOrderResponseDto = {
  data: Array<Order>;
  hasNextPage: boolean;
};

export type InfinityPaginationUserResponseDto = {
  data: Array<User>;
  hasNextPage: boolean;
};

export type LoginResponseDto = {
  token: string;
  refreshToken: string;
  tokenExpires: number;
  user: User;
};

export type Order = {
  customer: Customer;
  item: Array<OrderItem>;
  totalAmount: number;
  /**
   * Trạng thái đơn hàng trong lịch sử thay đổi
   */
  status: OrderStatusEnum;
  deliveredDate: string | null;
  expectedDeliveryDate: string | null;
  orderDate: string;
  deliveryAddress: string;
  orderCode: string;
  id: string;
  createdAt: string;
  updatedAt: string;
};

export type OrderDto = {
  id: string;
};

export type OrderHistory = {
  changeByUser: User;
  order: Order;
  /**
   * Trạng thái đơn hàng trong lịch sử thay đổi
   */
  status: OrderStatusEnum;
  id: string;
  createdAt: string;
  updatedAt: string;
};

export type OrderItem = {
  productName: string;
  quantity: number;
  unitPrice: number;
};

/**
 * Trạng thái đơn hàng trong lịch sử thay đổi
 */
export enum OrderStatusEnum {
  NEW_PENDING = "newPending",
  CONFIRMED = "confirmed",
  PACKING = "packing",
  SHIPPED = "shipped",
  IN_TRANSIT = "inTransit",
  DELIVERED = "delivered",
  CANCELLED = "cancelled",
  RETURN_REQUESTED = "returnRequested",
  RETURNED = "returned",
  FAILED_DELIVERY = "failedDelivery",
}

export type RefreshResponseDto = {
  token: string;
  refreshToken: string;
  tokenExpires: number;
};

export type Role = {
  id: string;
  name: string;
};

export type RoleDto = {
  id: {
    [key: string]: unknown;
  };
};

export type StatusDto = {
  id: {
    [key: string]: unknown;
  };
};

export type TotalResponseDto = {
  total: number;
};

export type UpdateCustomerDto = {
  note?: string;
  address?: string;
  email?: string;
  phone?: string;
  name?: string;
};

export type UpdateUserDto = {
  email?: string;
  password?: string;
  firstName?: string;
  lastName?: string;
  photo?: FileDto;
  role?: RoleDto;
  status?: StatusDto;
};

export type User = {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  photo: FileType;
  role: Role;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
};

export type UserDto = {
  id: string;
};

export type AuthControllerLoginV1Data = {
  requestBody: AuthEmailLoginDto;
  xCustomLang?: unknown;
};

export type AuthControllerLoginV1Response = LoginResponseDto;

export type AuthControllerRegisterV1Data = {
  requestBody: AuthRegisterLoginDto;
  xCustomLang?: unknown;
};

export type AuthControllerRegisterV1Response = void;

export type AuthControllerMeV1Data = {
  xCustomLang?: unknown;
};

export type AuthControllerMeV1Response = User;

export type AuthControllerUpdateV1Data = {
  requestBody: AuthUpdateDto;
  xCustomLang?: unknown;
};

export type AuthControllerUpdateV1Response = User;

export type AuthControllerDeleteV1Data = {
  xCustomLang?: unknown;
};

export type AuthControllerDeleteV1Response = void;

export type AuthControllerRefreshV1Data = {
  xCustomLang?: unknown;
};

export type AuthControllerRefreshV1Response = RefreshResponseDto;

export type AuthControllerLogoutV1Data = {
  xCustomLang?: unknown;
};

export type AuthControllerLogoutV1Response = void;

export type CustomersControllerCreateV1Data = {
  requestBody: CreateCustomerDto;
  xCustomLang?: unknown;
};

export type CustomersControllerCreateV1Response = Customer;

export type CustomersControllerFindAllV1Data = {
  address?: string;
  limit?: number;
  name?: string;
  page?: number;
  phone?: string;
  xCustomLang?: unknown;
};

export type CustomersControllerFindAllV1Response =
  InfinityPaginationCustomerResponseDto;

export type CustomersControllerFindByIdV1Data = {
  id: string;
  xCustomLang?: unknown;
};

export type CustomersControllerFindByIdV1Response = Customer;

export type CustomersControllerUpdateV1Data = {
  id: string;
  requestBody: UpdateCustomerDto;
  xCustomLang?: unknown;
};

export type CustomersControllerUpdateV1Response = Customer;

export type CustomersControllerRemoveV1Data = {
  id: string;
  xCustomLang?: unknown;
};

export type CustomersControllerRemoveV1Response = unknown;

export type FilesLocalControllerUploadFileV1Data = {
  formData: {
    file?: Blob | File;
  };
  xCustomLang?: unknown;
};

export type FilesLocalControllerUploadFileV1Response = FileResponseDto;

export type HomeControllerAppInfoData = {
  xCustomLang?: unknown;
};

export type HomeControllerAppInfoResponse = unknown;

export type OrderHistoriesControllerCreateV1Data = {
  requestBody: CreateOrderHistoryDto;
  xCustomLang?: unknown;
};

export type OrderHistoriesControllerCreateV1Response = OrderHistory;

export type OrderHistoriesControllerFindAllV1Data = {
  limit?: number;
  page?: number;
  xCustomLang?: unknown;
};

export type OrderHistoriesControllerFindAllV1Response =
  InfinityPaginationOrderHistoryResponseDto;

export type OrderHistoriesControllerFindByIdV1Data = {
  id: string;
  xCustomLang?: unknown;
};

export type OrderHistoriesControllerFindByIdV1Response = OrderHistory;

export type OrdersControllerCreateV1Data = {
  requestBody: CreateOrderDto;
  xCustomLang?: unknown;
};

export type OrdersControllerCreateV1Response = Order;

export type OrdersControllerFindAllV1Data = {
  code?: string;
  customer?: string;
  limit?: number;
  page?: number;
  status?: string;
  xCustomLang?: unknown;
};

export type OrdersControllerFindAllV1Response =
  InfinityPaginationOrderResponseDto;

export type OrdersControllerFindByIdV1Data = {
  id: string;
  xCustomLang?: unknown;
};

export type OrdersControllerFindByIdV1Response = Order;

export type OrdersControllerRemoveV1Data = {
  id: string;
  xCustomLang?: unknown;
};

export type OrdersControllerRemoveV1Response = unknown;

export type SatisticControllerCountOrderByTimeV1Data = {
  endDate: string;
  enumerateBy?: string;
  startDate: string;
  status?: string;
  xCustomLang?: unknown;
};

export type SatisticControllerCountOrderByTimeV1Response =
  EnumerateCountOrderDto;

export type SatisticControllerTotalRevenueV1Data = {
  endDate: string;
  startDate: string;
  status?: string;
  xCustomLang?: unknown;
};

export type SatisticControllerTotalRevenueV1Response = TotalResponseDto;

export type SatisticControllerTotalOrderV1Data = {
  endDate: string;
  startDate: string;
  status?: string;
  xCustomLang?: unknown;
};

export type SatisticControllerTotalOrderV1Response = TotalResponseDto;

export type UsersControllerCreateV1Data = {
  requestBody: CreateUserDto;
  xCustomLang?: unknown;
};

export type UsersControllerCreateV1Response = User;

export type UsersControllerFindAllV1Data = {
  filters?: string;
  limit?: number;
  page?: number;
  sort?: string;
  xCustomLang?: unknown;
};

export type UsersControllerFindAllV1Response =
  InfinityPaginationUserResponseDto;

export type UsersControllerFindOneV1Data = {
  id: string;
  xCustomLang?: unknown;
};

export type UsersControllerFindOneV1Response = User;

export type UsersControllerUpdateV1Data = {
  id: string;
  requestBody: UpdateUserDto;
  xCustomLang?: unknown;
};

export type UsersControllerUpdateV1Response = User;

export type UsersControllerRemoveV1Data = {
  id: string;
  xCustomLang?: unknown;
};

export type UsersControllerRemoveV1Response = void;
